config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  localized do
    root 'homepage#index'

    post '/listings/contact', to: 'listings#contact', as: 'listing_contact'
    post '/footers/new', to: 'footers#new', as: 'footer_new'

    namespace :account do
      resources :users, only: [:index,:update]
      resources :contacts ,only: [:index]
      resources :messages,only: [:index]
      resources :comments
    end

    resources :listings, only: [:index,:show,:new]
    resources :footers, only: [:index,:show,:new]

    devise_for :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :listings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user
  belongs_to :listing

  def self.generate(params,user)
    Contact.create(user_id: user.id , listing_id: params[:listing_id], message: params[:message])
    UserMailer.new_contact(params[:listing_id], user.email, params[:message]).deliver_now
  end

  def self.seller_contacts_for(user_id)
    Contact.joins('LEFT JOIN listings ON listings.id = contacts.listing_id').where(['listings.user_id = ?',user_id]).order('contacts.created_at DESC')
  end

  def self.buyer_messages_from(user_id)
    Contact.where(['user_id = ?', user_id]).order('contacts.created_at DESC')
  end

end

app/models/listing.rb
class Listing < ApplicationRecord
  validates_presence_of :title, :description, :picture
  has_many :comments
  belongs_to :category
  belongs_to :user
  mount_uploader :picture, PictureUploader

  def self.search(params)
    if params[:category_id]
      @listings = Listing.where(["category_id = ?", params[:category_id]])
    else
      @listings = Listing.where("title ILIKE :query", query: "%#{params[:keywords]}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :contacts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/account/account_controller.rb
class Account::AccountController < ApplicationController

  protect_from_forgery with: :exception
  layout 'account'
  before_action :authenticate_user!
end

app/controllers/account/comments_controller.rb
class Account::CommentsController < Account::AccountController

  def create
    @comment = Comment.create(
      user_id: current_user.id,
      content: params[:comment][:content],
      listing_id: params[:comment][:listing_id]
    )
    redirect_to listing_path(@comment.listing_id)
  end

end

app/controllers/account/contacts_controller.rb
class Account::ContactsController < Account::AccountController
  def index
    @contacts = Contact.seller_contacts_for(current_user) 
  end
end

app/controllers/account/messages_controller.rb
class Account::MessagesController < Account::AccountController

  def index
    @messages = Contact.buyer_messages_from(current_user) 
  end
end

app/controllers/account/users_controller.rb
class Account::UsersController < Account::AccountController

  def index
    @user = User.find(current_user.try(:id))
  end

  def update
    @user = User.find(current_user.try(:id))
      if user_params.has_key?(:email)
        if @user.update_attributes(user_params)
          redirect_to account_users_path
        else
          redirect_to account_users_path
        end
      else
        if @user.update_attributes(pass_params)
          redirect_to account_users_path
        else
          raise "fail"
        end
      end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end

    def pass_params
      params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  I18n.locale = :en

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sin_up, keys: [:first_name,:last_name,:email,:password,:password_confirmation])
  end

end

app/controllers/footers_controller.rb
class FootersController < ApplicationController

  def index
    @footer = Footer.search(params)
  end

  def show
    @footer = Footer.find(params[:id])
  end

  def new
    #redirect_to new_user_session_path unless current_user
    @footer = Footer.new
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.search(params)
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    #redirect_to new_user_session_path unless current_user
    @listing = Listing.new

  end

  def create
    @listing = Listing.create(task_params)

      respond_to do |format|
        if @listing.save
          format.html { redirect_to @listing, notice: 'Task was successfully created.' }
          format.json { render :show, status: :created, location: @listing }
        else
          format.html { render :new }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
  end

  def contact
    Contact.generate(params,current_user)
    render nothing:true
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:listing).permit(:title, :description, :picture,:category_id, :price).merge(user_id: current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def locale_select(lang)
    out = "<select class='form-control pull-right language' data-do='setLocale'>"
    I18n.available_locales.each do |loc|
      out += "<option value='#{url_for(locale: loc.to_s)}' #{'selected' if I18n.locale == loc}>#{loc}</option>"
    end

    out += "</select>"
    out.html_safe
  end

end

app/views/footer/new.html.haml
%h1 Conditions

app/views/homepage/index.html.haml
.row
  .col-xs-8.col-xs-offset-2.search
    %h2= t('main_baseline')
  = form_tag listings_path, method: :get , class: 'form form-horizontal' do
    .form-group
      .col-xs-10
        = text_field_tag 'keywords', nil, class: 'form-control',placeholder:t('search_placeholder')
      .col-xs-2
        = submit_tag t('search'), class: 'btn btn-success'

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listings</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= params[:controller]%>">
    <div class="header">
      <%= render partial: '/shared/header' %>
    </div>
    <div class="container">
      <div class='nav'>
        <%= render partial: '/account/shared/nav' %>
      </div>
      <div class="footer">
        <%= render partial: '/shared/footer' %>
      </div>
      <%= yield %>
    </div>
  </body>


  <script src="http://gbarillot-ynov-ruby.s3-website.eu-central-1.amazonaws.com/files/main.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listings</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= params[:controller]%>">
    <div class="header">
      <%= render partial: '/shared/header' %>
    </div>
    <div class="container content">
      <%= yield %>
    </di>
    %<hr>
    <div class="footer">
      <%= render partial: '/shared/footer' %>
    </div>
  </body>


  <script src="http://gbarillot-ynov-ruby.s3-website.eu-central-1.amazonaws.com/files/main.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/listings/_form.html.haml
= form_for listing, multipart:true do |f|
  - if listing.errors.any?
    #error_explanation
      %h2
        = pluralize(listing.errors.count, "error")
        prohibited this listing from being saved:
      %ul
        - listing.errors.full_messages.each do |message|
          %li= message
  %select.form-control{:name => "listing[category_id]"}
    - Category.all.each do |cat|
      %option{value:cat.id}=cat.title
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = f.file_field :picture

  .actions
    = f.submit

app/views/listings/index.html.haml
- @listings.each do |listing|
  %h2 #{listing.title}
  .row
    .col-xs-2
      =link_to listing_path(listing.id) do
        =image_tag listing.picture, height: '150',width: '150'
    .col-xs-10
      .label.label-primary
      =link_to listing.category.title, listings_path(category_id: listing.category.id)
      %br
      %p="#{listing.created_at}"
      %b
        ="#{listing.price} $"
      %p
        #{listing.description}
      .clearfix
        %br/
      %a.btn.btn-primary.pull-right{"data-do" => "showContactModal", "data-id" => "#{listing.id}","data-user" => "#{current_user.try(:id)}"}= t('contact')

  %hr


= render partial: '/modals/modal.html.haml'

app/views/listings/new.html.haml
%h1=t('create_listing')

= render partial: 'form', locals: {listing: @listing}

app/views/listings/show.html.haml
%h2= "Defail view for listing #{@listing.title} (#{@listing.category.title})"
=image_tag @listing.picture, height: '150', width: '150'
%br
="#{@listing.description}"
%hr
.col-xs-12
  .col-xs-6
    - @listing.comments.each do |c|
      %p="#{c.user.full_name} : #{c.content}"
  .col-xs-6
    %h4 New coment
    = form_tag account_comments_path do
      %textarea{name:'comment[content]'}
      %input{type:'hidden',name:'comment[listing_id]',value:"#{@listing.id}"}
      =submit_tag 'Submit', class:'btn btn-warning'

app/views/modals/_modal.html.haml
.modal.fade{"aria-labelledby" => "myModalLabel", "data-is" => "contactModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = form_tag listing_contact_path, data: {is: 'contactForm'} do
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#myModalLabel.modal-title= t('contact')
        .modal-body
          .form-group
            %label= t('your_message')
            = text_area_tag 'message', nil, class: 'form-control'
        .modal-footer
          = submit_tag t('send'), class: 'btn btn-primary pull-right'

app/views/shared/_footer.html.haml
.container
  .row
    .bottom
      .col-xs-12
        .col-xs-6
          %h3= link_to "Conditions générales de vente", footer_new_path
        .col-xs-6
          %h3= link_to "Mentions Légales"

app/views/shared/_header.html.haml
.container
  .row
    .top
      .col-xs-2
        %h1.title= link_to "Listings", root_path
      .col-xs-10.pull-right
        %a.btn.btn-success.pull-right{:href => new_listing_path}= t('create_listing')


        = locale_select(I18n.locale)
        - if current_user
          %a.my-account.pull-right{:href => "/account/users"}= t('my_account')
          %a.logout.pull-right{"data-method" => "delete", :href => "/users/sign_out"}= t('logout')
        - else
          %a.logout.pull-right{"data-method" => "create", :href => new_user_session_path}= t('sign_in')